using UnityEngine;using UnityEditor;using UnityEngine.SceneManagement;using System;using System.Collections;using System.Collections.Generic;using System.IO;using System.Linq;
namespace Mosswood.Editor {
 public static class MossLivingChecks {
  const string Output="C:/Users/nguye/Documents/Codex/2026-09-17/h-y-c-to-n-b-2/outputs/";
  static IEnumerator routine;static double next;static List<string> report;static Dictionary<string,string> saved;static Dictionary<string,bool> existed;static int errors;
  static readonly string[] suffixes={"seeds","shrines","x","y","boss","complete"};
  static string Prefix(int i)=>i==0?"DOAN.Mosswood.v1.":"DOAN.Mosswood.v2."+i+".";
  [MenuItem("DOAN/Living Forest/Verify terrain and campaign (Play Mode)")]
  public static void Run(){if(!EditorApplication.isPlaying)throw new InvalidOperationException("Enter Play Mode first.");Application.runInBackground=true;report=new List<string>();saved=new Dictionary<string,string>();existed=new Dictionary<string,bool>();for(int i=0;i<3;i++)foreach(var s in suffixes){string key=Prefix(i)+s;existed[key]=PlayerPrefs.HasKey(key);saved[key]=(s=="x"||s=="y")?PlayerPrefs.GetFloat(key).ToString(System.Globalization.CultureInfo.InvariantCulture):PlayerPrefs.GetInt(key).ToString();PlayerPrefs.DeleteKey(key);}errors=0;Application.logMessageReceived+=Log;routine=Suite();next=0;EditorApplication.update+=Tick;}
  static void Log(string text,string trace,LogType type){if(type==LogType.Error||type==LogType.Exception){errors++;report.Add("RUNTIME ERROR: "+text);}}
  static void Check(bool value,string description){report.Add((value?"PASS: ":"FAIL: ")+description);}
  static void Tick(){EditorApplication.QueuePlayerLoopUpdate();if(EditorApplication.timeSinceStartup<next)return;if(!EditorApplication.isPlaying){report.Add("FAIL: Verification interrupted");Finish();return;}try{if(!routine.MoveNext()){Finish();return;}next=EditorApplication.timeSinceStartup+(routine.Current is float f?f:.1f);}catch(Exception e){report.Add("FAIL: "+e);Finish();}}
  static IEnumerator Suite(){for(int map=0;map<3;map++){
   SceneManager.LoadScene(MossJourney.Scenes[map]);yield return 1f;var j=UnityEngine.Object.FindAnyObjectByType<MossJourney>();int attempts=0;while((!j||j.Combat==null)&&attempts++<30){yield return .1f;j=UnityEngine.Object.FindAnyObjectByType<MossJourney>();}
   Check(j&&j.chapter==map&&j.Combat!=null,"Map "+map+" loads with initialized gameplay");var profile=UnityEngine.Object.FindAnyObjectByType<MossTerrainProfile>();Check(profile&&profile.surface.Max(p=>p.y)-profile.surface.Min(p=>p.y)>2,"Map "+map+" substantial elevation changes");
   var wildlife=UnityEngine.Object.FindObjectsByType<MossWildlife>(FindObjectsSortMode.None);var giants=UnityEngine.Object.FindObjectsByType<MossColossus>(FindObjectsSortMode.None);Check(wildlife.Length==68&&giants.Length==2,"Map "+map+" 68 ambient creatures and 2 colossal rigs");Check(wildlife.Where(w=>w.species==MossWildlife.Species.Bat).All(w=>w.frames.Length==3&&w.frames.All(f=>f)),"Map "+map+" bat flight frames assigned");
   int missing=UnityEngine.Object.FindObjectsByType<GameObject>(FindObjectsSortMode.None).Sum(GameObjectUtility.GetMonoBehavioursWithMissingScriptCount);Check(missing==0,"Map "+map+" no missing scripts");
   Check(j.panel.activeSelf&&j.traveler.Locked,"Map "+map+" menu locks movement");j.Continue();yield return .2f;
   Vector3 first=wildlife[0].transform.position;Vector3 firstGiant=giants[0].transform.localPosition;Vector3 firstScale=giants[0].transform.localScale;yield return 1f;Check(Vector3.Distance(first,wildlife[0].transform.position)>.01f,"Map "+map+" wildlife actually moves");Check(Vector3.Distance(firstGiant,giants[0].transform.localPosition)> .00001f||Vector3.Distance(firstScale,giants[0].transform.localScale)> .00001f,"Map "+map+" colossus rig actually animates");
   j.Pause();first=wildlife[0].transform.position;yield return .3f;Check(Vector3.Distance(first,wildlife[0].transform.position)<.001f&&!j.Combat.Hurt(1),"Map "+map+" pause freezes wildlife and damage");j.Continue();
   PhysicsChecks(j,profile,map);
   j.traveler.Warp(j.seeds[0].position);yield return .15f;Check(j.SeedCount==1&&PlayerPrefs.GetInt(j.SavePrefix+"seeds")==1,"Map "+map+" repositioned collectible saves");
   j.traveler.Warp(new Vector3(j.finishX+1,-1.9f));Check(!j.TryComplete(),"Map "+map+" shrines still gate completion");for(int i=0;i<j.shrines.Length;i++)j.ActivateShrine(i);j.Respawn();Check(Mathf.Abs(j.traveler.transform.position.y-(profile.HeightAt(j.shrines[2].position.x)+1.4f))<.1f,"Map "+map+" checkpoint aligned with new terrain");
   if(map>0){var boss=j.guardian;j.traveler.Warp(new Vector3(j.finishX+1,-2.4f));Check(!j.TryComplete(),"Map "+map+" guardian gates exit");j.traveler.Warp(new Vector3(128,-2.4f));yield return .2f;int hp=boss.Health;bool fired=j.Combat.Fire();yield return .6f;Check(fired&&boss.Health<hp,"Map "+map+" projectile still hits guardian");boss.TakeHit(boss.maxHealth/2);Check(boss.Enraged,"Map "+map+" guardian phase II");j.Respawn();Check(boss.Health==boss.maxHealth&&!boss.Engaged,"Map "+map+" encounter reset");j.traveler.Warp(new Vector3(128,-2.4f));yield return .2f;boss.TakeHit(100);Check(boss.Defeated&&PlayerPrefs.GetInt(j.SavePrefix+"boss")==1,"Map "+map+" boss defeat persists");}
   j.traveler.Warp(new Vector3(j.finishX+1,-2.4f));Check(j.TryComplete()&&j.panel.activeSelf,"Map "+map+" completion menu");j.Continue();Check(j.IsPlaying,"Map "+map+" exploration resumes");SceneManager.LoadScene(MossJourney.Scenes[map]);yield return 1f;j=UnityEngine.Object.FindAnyObjectByType<MossJourney>();Check(j.SeedCount==1&&j.ShrineCount==3&&j.Completed,"Map "+map+" saved campaign restored");
  }Check(errors==0,"No runtime errors during Living Forest verification");}
  static void PhysicsChecks(MossJourney j,MossTerrainProfile profile,int map){
   var mode=Physics2D.simulationMode;var rb=j.traveler.GetComponent<Rigidbody2D>();var box=j.traveler.GetComponent<BoxCollider2D>();bool enabled=j.traveler.enabled;var start=j.traveler.transform.position;
   try{Physics2D.simulationMode=SimulationMode2D.Script;j.traveler.enabled=false;rb.gravityScale=3;
    foreach(float x in new[]{0f,20f,48f,60f,70f,95f,112f,138f}){j.traveler.Warp(new Vector3(x,profile.HeightAt(x)+1.1f));Physics2D.SyncTransforms();for(int k=0;k<80;k++){rb.linearVelocity=new Vector2(0,rb.linearVelocity.y);Physics2D.Simulate(.02f);}Check(rb.position.y>profile.HeightAt(rb.position.x)+.5f&&rb.position.y<profile.HeightAt(rb.position.x)+1.35f,"Map "+map+" solid slope/ground at x="+x);}
    var ledge=UnityEngine.Object.FindObjectsByType<BoxCollider2D>(FindObjectsSortMode.None).Where(c=>c.usedByEffector).OrderBy(c=>c.bounds.center.x).First();float lx=ledge.bounds.center.x;float expected=ledge.bounds.max.y+box.bounds.extents.y-box.offset.y*j.traveler.transform.lossyScale.y;
    j.traveler.Warp(new Vector3(lx,profile.HeightAt(lx)+.9f));Physics2D.SyncTransforms();for(int k=0;k<30;k++)Physics2D.Simulate(.02f);rb.linearVelocity=new Vector2(0,11.5f);for(int k=0;k<120;k++)Physics2D.Simulate(.02f);Check(Mathf.Abs(rb.position.y-expected)<.1f,"Map "+map+" one-way ledge real physics landing (y="+rb.position.y+", expected="+expected+")");
    j.traveler.Warp(new Vector3(0,-1.9f));Physics2D.SyncTransforms();float jumpCooldown=0;for(int k=0;k<2300&&rb.position.x<147&&rb.position.y> -8;k++){var b=box.bounds;bool grounded=Physics2D.OverlapBox(new Vector2(b.center.x,b.min.y-.05f),new Vector2(b.size.x*.8f,.15f),0,64);jumpCooldown-=.02f;if(grounded&&jumpCooldown<=0&&(profile.IsGap(rb.position.x+.8f)||profile.IsGap(rb.position.x+1.1f))){rb.linearVelocity=new Vector2(rb.linearVelocity.x,11.5f);jumpCooldown=.7f;}rb.linearVelocity=new Vector2(5.8f,Mathf.Max(rb.linearVelocity.y,-20));Physics2D.Simulate(.02f);}
    Check(rb.position.x>=147&&rb.position.y> -8,"Map "+map+" continuous playable route incl. slopes and gap jumps (end="+rb.position+")");
   }finally{Physics2D.simulationMode=mode;j.traveler.enabled=enabled;j.traveler.Warp(start);}
  }
  static void Finish(){EditorApplication.update-=Tick;Application.logMessageReceived-=Log;for(int i=0;i<3;i++)foreach(var s in suffixes){string key=Prefix(i)+s;if(!existed[key])PlayerPrefs.DeleteKey(key);else if(s=="x"||s=="y")PlayerPrefs.SetFloat(key,float.Parse(saved[key],System.Globalization.CultureInfo.InvariantCulture));else PlayerPrefs.SetInt(key,int.Parse(saved[key]));}PlayerPrefs.Save();Directory.CreateDirectory(Output);File.WriteAllLines(Output+"living-forest-verification.txt",report);Debug.Log(string.Join("\n",report));EditorApplication.isPlaying=false;}
 }
}



