using UnityEngine;
namespace Mosswood {
 public class MossGuardian : MonoBehaviour {
  public MossJourney journey;public string guardianName="NGƯỜI GIỮ RỄ";public int maxHealth=24;public float arenaLeft=119,arenaRight=143;public Transform body,leftArm,rightArm,core;public SpriteRenderer warning;public Collider2D hitbox;
  public int Health {get;private set;}public bool Defeated=>Health<=0;public bool Engaged {get;private set;}public string Cue {get;private set;}="";
  public bool Enraged=>Health<=maxHealth/2;float timer,flash;int attack;Vector3 origin,bodyScale;float targetX;enum State{Idle,Telegraph,Recover,Dead}State state;
  void Start(){origin=transform.position;bodyScale=body.localScale;Health=maxHealth;warning.enabled=false;if(PlayerPrefs.GetInt(journey.SavePrefix+"boss",0)==1)RestoreDefeated();}
  void Update(){if(!journey.IsPlaying||Defeated)return;float dt=Time.deltaTime;flash=Mathf.Max(0,flash-dt);body.localPosition=Vector3.up*(Mathf.Sin(Time.time*1.8f)*.12f);body.localScale=bodyScale*(1+Mathf.Sin(Time.time*2)*.025f);leftArm.localRotation=Quaternion.Euler(0,0,(state==State.Telegraph?-40:0)+Mathf.Sin(Time.time*2)*10);rightArm.localRotation=Quaternion.Euler(0,0,(state==State.Telegraph?40:0)-Mathf.Sin(Time.time*2)*10);core.localScale=Vector3.one*(.8f+Mathf.Sin(Time.time*5)*.1f+flash);if(!Engaged){if(journey.traveler.transform.position.x>arenaLeft){Engaged=true;timer=1.4f;Cue="J / CHUỘT TRÁI  ·  BẮN ÁNH SÁNG";}return;}if(journey.traveler.transform.position.x<arenaLeft-7){ResetEncounter();return;}timer-=dt;if(timer>0)return;
   if(state==State.Idle||state==State.Recover){attack=(attack+1)%2;targetX=journey.traveler.transform.position.x;warning.enabled=true;warning.transform.position=new Vector3(targetX,-3.02f,0);warning.transform.localScale=new Vector3(attack==0?5:2,.13f,1);Cue=attack==0?"RỄ TRỖI DẬY · NHẢY HOẶC LƯỚT!":"MƯA GAI · DI CHUYỂN ĐỂ NÉ!";timer=Enraged?.75f:1.1f;state=State.Telegraph;leftArm.localRotation=Quaternion.Euler(0,0,-45);}
   else{warning.enabled=false;if(attack==0){if(Mathf.Abs(journey.traveler.transform.position.x-targetX)<2.5f&&journey.traveler.transform.position.y< -1.1f)journey.Combat.Hurt(1);MossEffect.Burst(journey.Combat.lightSprite,journey.Combat.lightMaterial,new Vector3(targetX,-2.8f),new Color(1,.65f,.25f),16);for(int i=-1;i<=1;i+=2)MossBolt.Spawn(journey.Combat.lightSprite,journey.Combat.lightMaterial,new Vector3(targetX,-2.65f),Vector2.right*i*5,true,journey,1);}else{Vector2 aim=(journey.traveler.transform.position-core.position).normalized;for(int i=Enraged?-2:-1;i<=(Enraged?2:1);i++){Vector2 dir=Quaternion.Euler(0,0,i*16)*aim;MossBolt.Spawn(journey.Combat.lightSprite,journey.Combat.lightMaterial,core.position,dir*(Enraged?5.8f:4.5f),true,journey,1);}}Cue="LÕI ĐANG MỞ · PHẢN CÔNG!";state=State.Recover;timer=Enraged?1.35f:2f;Camera.main.GetComponent<MossCamera>()?.Shake(.1f);}
  }
  public bool TakeHit(int amount){if(!journey.IsPlaying||!Engaged||Defeated||amount<=0)return false;Health=Mathf.Max(0,Health-amount);flash=.25f;if(Defeated){state=State.Dead;Engaged=false;warning.enabled=false;hitbox.enabled=false;body.gameObject.SetActive(false);MossBolt.Clear();MossEffect.Burst(journey.Combat.lightSprite,journey.Combat.lightMaterial,transform.position+Vector3.up,new Color(1,.8f,.35f),30);PlayerPrefs.SetInt(journey.SavePrefix+"boss",1);PlayerPrefs.Save();journey.Notify("Người canh giữ đã yên giấc. Cổng cuối màn đã mở.");}return true;}
  public void ResetEncounter(){if(Defeated)return;Health=maxHealth;Engaged=false;state=State.Idle;timer=1.4f;warning.enabled=false;transform.position=origin;MossBolt.Clear();}
  void RestoreDefeated(){Health=0;state=State.Dead;body.gameObject.SetActive(false);hitbox.enabled=false;}
 }
}

